# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: eos-micro-services-admin
# spec:
#   rules:
#   - host: {{ .Values.ingress.host }}
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: eos-micro-services-admin-service
#             port:
#               number: 8090
#   ingressClassName: nginx

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eos-micro-services-admin
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: eos-micro-services-admin-service
            port:
              number: 8080
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: {{ .Values.ingress.host }}-secret



